version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # Puerto AMQP
      - "15672:15672"   # Interfaz web
    networks:
      - taller_net

networks:
  taller_net:
    driver: bridge

