version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # Puerto AMQP (para productores y consumidores)
      - "15672:15672"   # Interfaz web de administración
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - taller_net


networks:
  taller_net:
    driver: bridge
